services:
  dexcom-sync:
    image: ghcr.io/kirbyok/dexcom_sync:latest
    container_name: dexcom-sync
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "main.py", "continuous"]
  
  glooko-sync:
    image: ghcr.io/kirbyok/dexcom_sync:latest
    container_name: glooko-sync
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "glooko_main.py", "continuous"]
